name: checks

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
      - run: |
          yarn check
